# Change these first
owner: siddhantw # Your GitHub organization or username, where this repository lives
repo: siddhantw.github.io # The name of this repository

sites:
  - name: Siddhant Wadhwani Homepage
    url: https://siddhantwadhwani.com
    assignees:
      - siddhantw 
  - name: Mark Monitor Website
    url: https://markmonitor.com
    assignees:
      - siddhantw 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /siddhantw.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Uptime Monitor"
  introTitle: "Central place to find all the uptime status and respone times for my websites"
  introMessage: I love open source!
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://siddhantwadhwani.com
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
